blank_issues_enabled: false
contact_links:
  - name: Questions and help
    url: https://github.com/luisgsluis/homeassistant-koolnova/discussions
    about: Ask questions or discuss ideas in GitHub Discussions.
